// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://feaqypesoprxrzuhhpwu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZlYXF5cGVzb3ByeHJ6dWhocHd1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTYxMDA1ODAsImV4cCI6MjA3MTY3NjU4MH0.oBb-mRILhROvRW8pmjBWf6fM5lsDY9T2M021HsSueww";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});